input {
  beats {
    port => 5044
  }
}

filter {
  # parse JSON (already structured, but safe)
  json {
    source => "message"
    skip_on_invalid_json => true
  }

  mutate {
    add_field => { "environment" => "dev" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}